apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tensorflow-housing-app

configurations:
  - servicemonitor-matchlabels.yaml

labels:
  - includeSelectors: true
    pairs:
      app: tensorflow-housing-app

resources:
- ../../base
