apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bike-rental-app

configurations:
  - servicemonitor-matchlabels.yaml

labels:
  - includeSelectors: true
    pairs:
      app: bike-rental-app

resources:
- ../../base
